[[headers]]
  for = "/*.js"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''

[[headers]]
  for = "/*.css"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''

[[headers]]
  for = "/static/*"
  [headers.values]
	cache-control = '''
	public,
	max-age=31536000,
	immutable'''
