---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: site/content/about.md
  label: About
  match: "**/*"
- type: document
  path: site/content/meta.md
  label: Site Metadata
- type: heading
  label: Pages
- type: document
  path: site/content/news.md
  label: News
- type: document
  path: site/content/careers.md
  label: Careers
- type: document
  path: site/content/contact.md
  label: Contact
- type: document
  path: site/content/404.md
  label: '404'
upload_dir: static/assets
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
